version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: banking
    restart: always
    ports:
      - "8005:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: banking
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    container_name: banking_db
    restart: always
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: banking
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
